In [5]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series
from datetime import timedelta
import time
from datetime import datetime

M_data = pd.DataFrame(pd.read_csv("/Users/kuoloading/Downloads/91ForNTUDataSet/MemberData.csv",low_memory=False))
O_data = pd.DataFrame(pd.read_csv("/Users/kuoloading/Downloads/91ForNTUDataSet/OrderData.csv",low_memory=False))
OS_data = pd.DataFrame(pd.read_csv("/Users/kuoloading/Downloads/91ForNTUDataSet/OrderSlaveData.csv",low_memory=False))
one = pd.DataFrame(pd.read_csv("/Users/kuoloading/Downloads/91ForNTUDataSet/123_new/activityPageView_2018-08-05.csv",low_memory=False))

In [6]:
#M_data['RegisterDateTime'] = pd.to_datetime(M_data['RegisterDateTime'].astype(str).str[0:19], format = "%Y-%m-%d %H:%M:%S") + timedelta(hours = 8 )
M_data['RegisterDateTime1'] = pd.to_datetime(M_data['RegisterDateTime'].astype(str).str[0:10], format = "%Y-%m-%d") + timedelta(hours = 8 )
OS_data['TradesDateTime1'] = pd.to_datetime(OS_data['TradesDateTime'].astype(str).str[0:19], format = "%Y-%m-%d %H:%M:%S") + timedelta(hours = 8 )
O_data['TradesDateTime1'] = pd.to_datetime(O_data['TradesDateTime'].astype(str).str[0:19], format = "%Y-%m-%d %H:%M:%S") + timedelta(hours = 8 )

In [7]:
indexStatus = O_data[O_data['Status'] != 'Finish'].index
indexStatus[0:20]
print(len(indexStatus))
O_data.drop(indexStatus , inplace=True)

153274

In [8]:
sort = O_data.sort_values(by=['MemberID',"TradesGroupCode"])
sort.head(12)

,TradesGroupCode,TradesDateTime,ChannelType,ChannelDetail,PaymentType,ShippingType,TsCount,Qty,TotalSalesAmount,TotalPrice,TotalDiscount,TotalPromotionDiscount,TotalCouponDiscount,TotalLoyaltyDiscount,Status,MemberID,TradesDateTime1
497353,TG190626A00622,2019-06-26 00:31:11.430,OfficialECom,AndroidApp,CreditCardInstallment,FamilyPickup,4,4,2850,3200,-350,-250,-100,0,Finish,%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf90...,2019-06-26 08:31:11
116350,0620180526004,2018-05-26 14:48:00,Pos,6,Cash,Store,1,1,1380,1380,0,0,0,0,Finish,%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%...,2018-05-26 22:48:00
329440,TG190412U00364,2019-04-12 18:23:27.743,OfficialECom,MobileWeb,SevenEleven,SevenEleven,4,4,3160,3160,0,0,0,0,Finish,%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN...,2019-04-13 02:23:27
285397,TG190904S00363,2019-09-04 16:19:02.423,OfficialECom,iOSApp,LinePay,FamilyPickup,1,1,1900,1900,0,0,0,0,Finish,%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B...,2019-09-05 00:19:02
294518,TG160623210407,2016-06-23 21:22:27.417,OfficialECom,MobileWeb,SevenEleven,SevenEleven,1,1,1280,1380,-100,-100,0,0,Finish,%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWg...,2016-06-24 05:22:27
106353,0520170928001,2017-09-28 14:38:00,Pos,5,Cash,Store,6,6,3758,3800,-42,-42,0,0,Finish,%2B%2B6ZXiIdakH%2B77WllacG4cehkRZkwBnSIX2XvAro...,2017-09-28 22:38:00
20193,1520170729008,2017-07-29 17:24:00,Pos,015,Cash,Store,3,3,3359,3410,-51,-51,0,0,Finish,%2B%2B6bo8s3RbG5E3%2FFlzz1bg7Q7D3rdOd00L7AXTUH...,2017-07-30 01:24:00
116861,0320180603019,2018-06-03 17:21:00,Pos,3,Cash,Store,1,1,1422,1580,-158,-158,0,0,Finish,%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbY...,2018-06-04 01:21:00
33360,0320180603020,2018-06-03 17:22:00,Pos,3,Cash,Store,1,1,10,20,-10,-10,0,0,Finish,%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbY...,2018-06-04 01:22:00
41003,0520181006028,2018-10-06 20:51:00,Pos,5,Cash,Store,1,1,1380,1380,0,0,0,0,Finish,%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbY...,2018-10-07 04:51:00
115029,1520180429029,2018-04-29 20:42:00,Pos,15,Cash,Store,4,4,3484,3560,-76,-76,0,0,Finish,%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbY...,2018-04-30 04:42:00
32556,1520180521020,2018-05-21 19:05:00,Pos,015,Cash,Store,2,2,2960,2960,0,0,0,0,Finish,%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbY...,2018-05-22 03:05:00

In [9]:
monetary = sort.pivot_table('TotalSalesAmount', index='MemberID',aggfunc="mean")
#age.to_csv("/Users/kuoloading/Downloads/age.csv")
monetary.head(10)

                                                    TotalSalesAmount
MemberID
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909...       2850.000000
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2...       1380.000000
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7...       3160.000000
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%...       1900.000000
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf...       1280.000000
%2B%2B6ZXiIdakH%2B77WllacG4cehkRZkwBnSIX2XvAroT...       3758.000000
%2B%2B6bo8s3RbG5E3%2FFlzz1bg7Q7D3rdOd00L7AXTUHy...       3359.000000
%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbYC...       1976.857143
%2B%2B8lPULC%2BdY%2F3MWf4kbymzr1cx%2B3Eaktr2fvQ...       1726.000000
%2B%2B9RCToUG%2F8jRD0EcLzfsQPEiC7vN64HMkzGjPxlk...       1280.000000

In [10]:
monetary_max = sort.pivot_table('TotalSalesAmount', index='MemberID',aggfunc="max")
#age.to_csv("/Users/kuoloading/Downloads/age.csv")
monetary_max.head(10)

                                                    TotalSalesAmount
MemberID
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909...              2850
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2...              1380
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7...              3160
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%...              1900
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf...              1280
%2B%2B6ZXiIdakH%2B77WllacG4cehkRZkwBnSIX2XvAroT...              3758
%2B%2B6bo8s3RbG5E3%2FFlzz1bg7Q7D3rdOd00L7AXTUHy...              3359
%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbYC...              3484
%2B%2B8lPULC%2BdY%2F3MWf4kbymzr1cx%2B3Eaktr2fvQ...              1726
%2B%2B9RCToUG%2F8jRD0EcLzfsQPEiC7vN64HMkzGjPxlk...              1280

In [11]:
frequency = sort.pivot_table('TradesGroupCode', index='MemberID',aggfunc="count")
frequency.head(10)

                                                    TradesGroupCode
MemberID
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909...                1
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2...                1
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7...                1
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%...                1
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf...                1
%2B%2B6ZXiIdakH%2B77WllacG4cehkRZkwBnSIX2XvAroT...                1
%2B%2B6bo8s3RbG5E3%2FFlzz1bg7Q7D3rdOd00L7AXTUHy...                1
%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbYC...                7
%2B%2B8lPULC%2BdY%2F3MWf4kbymzr1cx%2B3Eaktr2fvQ...                1
%2B%2B9RCToUG%2F8jRD0EcLzfsQPEiC7vN64HMkzGjPxlk...                1

In [101]:
index = []
index1 = []
index2 = []
index5 = []
index6 = []
frequency['TradesGroupCode']
for i in range(len(frequency)):
    if frequency['TradesGroupCode'][i] > 1:
        index += [i]
    if frequency['TradesGroupCode'][i] > 2:
        index1 += [i]
    if frequency['TradesGroupCode'][i] > 3:
        index2 += [i]
    if frequency['TradesGroupCode'][i] > 5:
        index5 += [i]
    if frequency['TradesGroupCode'][i] > 6:
        index6 += [i]

In [102]:
len(index6)

5381

In [81]:
index2

[7,
 17,
 35,
 54,
 77,
 97,
 102,
 106,
 121,
 138,
 150,
 157,
 170,
 177,
 181,
 192,
 194,
 199,
 264,
 280,
 287,
 289,
 298,
 303,
 308,
 311,
 333,
 347,
 353,
 355,
 357,
 367,
 391,
 395,
 402,
 425,
 427,
 429,
 443,
 457,
 465,
 469,
 472,
 473,
 496,
 499,
 503,
 509,
 510,
 512,
 536,
 554,
 563,
 589,
 590,
 592,
 594,
 633,
 634,
 649,
 656,
 657,
 662,
 665,
 670,
 673,
 702,
 705,
 714,
 718,
 726,
 733,
 739,
 744,
 762,
 764,
 766,
 767,
 785,
 793,
 795,
 800,
 802,
 812,
 814,
 820,
 833,
 835,
 840,
 853,
 870,
 886,
 892,
 894,
 896,
 905,
 911,
 919,
 920,
 947,
 950,
 967,
 968,
 980,
 997,
 1009,
 1019,
 1041,
 1042,
 1082,
 1083,
 1084,
 1104,
 1106,
 1119,
 1122,
 1137,
 1144,
 1156,
 1191,
 1209,
 1211,
 1215,
 1216,
 1217,
 1222,
 1245,
 1251,
 1286,
 1289,
 1294,
 1295,
 1308,
 1313,
 1324,
 1335,
 1347,
 1348,
 1350,
 1354,
 1373,
 1377,
 1389,
 1404,
 1484,
 1491,
 1492,
 1502,
 1517,
 1520,
 1521,
 1542,
 1543,
 1549,
 1564,
 1578,
 1582,
 1585,
 1594,
 1598,
 1600,
 1601,
 1607,
 1608,
 1613,
 1635,
 1642,
 1644,
 1649,
 1659,
 1674,
 1681,
 1695,
 1702,
 1703,
 1707,
 1710,
 1717,
 1719,
 1722,
 1727,
 1737,
 1741,
 1743,
 1745,
 1754,
 1757,
 1759,
 1762,
 1774,
 1795,
 1797,
 1804,
 1815,
 1820,
 1821,
 1823,
 1842,
 1851,
 1854,
 1858,
 1863,
 1867,
 1870,
 1899,
 1919,
 1925,
 1934,
 1939,
 1945,
 1951,
 1962,
 1965,
 1971,
 1976,
 2021,
 2026,
 2043,
 2047,
 2048,
 2058,
 2062,
 2093,
 2106,
 2115,
 2117,
 2119,
 2120,
 2134,
 2150,
 2165,
 2178,
 2185,
 2188,
 2218,
 2220,
 2238,
 2246,
 2259,
 2261,
 2267,
 2285,
 2299,
 2316,
 2318,
 2319,
 2333,
 2343,
 2359,
 2362,
 2363,
 2365,
 2392,
 2395,
 2399,
 2402,
 2420,
 2424,
 2428,
 2446,
 2467,
 2468,
 2473,
 2482,
 2502,
 2507,
 2517,
 2531,
 2536,
 2545,
 2572,
 2580,
 2581,
 2584,
 2597,
 2621,
 2636,
 2637,
 2651,
 2653,
 2666,
 2683,
 2684,
 2689,
 2691,
 2696,
 2697,
 2705,
 2733,
 2738,
 2761,
 2785,
 2792,
 2810,
 2828,
 2835,
 2840,
 2843,
 2853,
 2859,
 2871,
 2876,
 2893,
 2930,
 2940,
 2942,
 2952,
 2959,
 2961,
 2964,
 2975,
 2992,
 3013,
 3038,
 3041,
 3049,
 3052,
 3055,
 3060,
 3066,
 3081,
 3084,
 3090,
 3098,
 3113,
 3133,
 3142,
 3145,
 3147,
 3148,
 3154,
 3155,
 3161,
 3169,
 3201,
 3204,
 3219,
 3228,
 3234,
 3237,
 3251,
 3263,
 3271,
 3274,
 3289,
 3292,
 3321,
 3335,
 3357,
 3370,
 3371,
 3394,
 3424,
 3432,
 3437,
 3443,
 3451,
 3462,
 3473,
 3477,
 3478,
 3479,
 3483,
 3487,
 3492,
 3504,
 3510,
 3514,
 3527,
 3530,
 3546,
 3556,
 3583,
 3587,
 3588,
 3589,
 3590,
 3594,
 3595,
 3605,
 3616,
 3622,
 3623,
 3634,
 3638,
 3644,
 3647,
 3649,
 3650,
 3652,
 3663,
 3666,
 3669,
 3689,
 3692,
 3702,
 3708,
 3713,
 3721,
 3727,
 3728,
 3735,
 3743,
 3749,
 3757,
 3761,
 3796,
 3802,
 3808,
 3811,
 3820,
 3848,
 3850,
 3862,
 3887,
 3891,
 3894,
 3918,
 3919,
 3932,
 3934,
 3935,
 3949,
 3971,
 3985,
 3992,
 4004,
 4005,
 4046,
 4047,
 4065,
 4099,
 4125,
 4128,
 4132,
 4136,
 4141,
 4147,
 4154,
 4157,
 4172,
 4178,
 4183,
 4184,
 4186,
 4204,
 4205,
 4208,
 4217,
 4223,
 4226,
 4275,
 4295,
 4300,
 4310,
 4317,
 4318,
 4324,
 4335,
 4339,
 4346,
 4356,
 4382,
 4399,
 4415,
 4429,
 4451,
 4456,
 4470,
 4480,
 4487,
 4504,
 4507,
 4509,
 4517,
 4523,
 4524,
 4530,
 4535,
 4539,
 4545,
 4555,
 4570,
 4587,
 4593,
 4600,
 4639,
 4659,
 4679,
 4684,
 4689,
 4701,
 4702,
 4710,
 4712,
 4735,
 4738,
 4740,
 4746,
 4769,
 4771,
 4779,
 4789,
 4804,
 4811,
 4822,
 4828,
 4831,
 4832,
 4837,
 4841,
 4851,
 4879,
 4884,
 4893,
 4895,
 4898,
 4915,
 4920,
 4921,
 4926,
 4930,
 4937,
 4946,
 4949,
 4951,
 4965,
 4968,
 4996,
 5000,
 5004,
 5025,
 5056,
 5108,
 5125,
 5126,
 5128,
 5149,
 5150,
 5168,
 5170,
 5180,
 5182,
 5188,
 5192,
 5195,
 5197,
 5210,
 5211,
 5213,
 5222,
 5226,
 5237,
 5259,
 5263,
 5278,
 5288,
 5290,
 5298,
 5322,
 5336,
 5338,
 5352,
 5357,
 5363,
 5365,
 5372,
 5373,
 5376,
 5381,
 5387,
 5389,
 5394,
 5411,
 5414,
 5462,
 5474,
 5504,
 5506,
 5531,
 5561,
 5562,
 5568,
 5571,
 5603,
 5606,
 5607,
 5633,
 5648,
 5654,
 5692,
 5705,
 5717,
 5724,
 5732,
 5739,
 5743,
 5749,
 5754,
 5765,
 5770,
 5771,
 5779,
 5807,
 5809,
 5817,
 5823,
 5831,
 5834,
 5840,
 5886,
 5890,
 5897,
 5906,
 5921,
 5928,
 5930,
 5943,
 5954,
 5971,
 5973,
 5975,
 5976,
 5981,
 5991,
 6005,
 6008,
 6018,
 6037,
 6053,
 6069,
 6089,
 6093,
 6097,
 6103,
 6132,
 6141,
 6177,
 6189,
 6190,
 6191,
 6212,
 6221,
 6242,
 6250,
 6265,
 6270,
 6278,
 6289,
 6321,
 6326,
 6342,
 6359,
 6362,
 6370,
 6380,
 6384,
 6392,
 6400,
 6413,
 6414,
 6423,
 6429,
 6433,
 6436,
 6437,
 6439,
 6442,
 6451,
 6454,
 6457,
 6462,
 6470,
 6478,
 6479,
 6490,
 6514,
 6525,
 6527,
 6528,
 6536,
 6561,
 6567,
 6574,
 6580,
 6584,
 6606,
 6620,
 6645,
 6660,
 6665,
 6668,
 6681,
 6715,
 6719,
 6724,
 6725,
 6743,
 6750,
 6755,
 6766,
 6768,
 6771,
 6781,
 6789,
 6799,
 6800,
 6813,
 6821,
 6835,
 6841,
 6845,
 6857,
 6864,
 6870,
 6877,
 6884,
 6886,
 6891,
 6894,
 6907,
 6927,
 6928,
 6934,
 6936,
 6949,
 6962,
 6971,
 6977,
 6985,
 6992,
 6996,
 6997,
 7019,
 7022,
 7023,
 7035,
 7043,
 7047,
 7069,
 7075,
 7092,
 7109,
 7111,
 7112,
 7124,
 7131,
 7144,
 7145,
 7163,
 7166,
 7181,
 7183,
 7202,
 7215,
 7230,
 7257,
 7265,
 7267,
 7269,
 7293,
 7299,
 7301,
 7309,
 7322,
 7325,
 7331,
 7348,
 7353,
 7362,
 7370,
 7374,
 7397,
 7404,
 7412,
 7413,
 7418,
 7431,
 7434,
 7435,
 7448,
 7471,
 7477,
 7485,
 7486,
 7488,
 7493,
 7503,
 7527,
 7529,
 7534,
 7535,
 7544,
 7547,
 7551,
 7552,
 7556,
 7558,
 7560,
 7571,
 7591,
 7593,
 7600,
 7603,
 7626,
 7646,
 7667,
 7678,
 7680,
 7686,
 7721,
 7737,
 7739,
 7744,
 7747,
 7749,
 7759,
 7760,
 7771,
 7774,
 7786,
 7794,
 7802,
 7835,
 7842,
 7853,
 7862,
 7866,
 7870,
 7891,
 7906,
 7926,
 7937,
 7941,
 7943,
 7947,
 7951,
 7967,
 7989,
 7991,
 7997,
 8008,
 8048,
 8052,
 8066,
 8069,
 8107,
 8110,
 8111,
 8113,
 8116,
 8117,
 8120,
 8122,
 8124,
 8126,
 8139,
 8141,
 8144,
 8146,
 8148,
 8152,
 8153,
 8160,
 8174,
 8195,
 8197,
 8209,
 8210,
 8215,
 8224,
 8236,
 8239,
 8247,
 8248,
 8257,
 8267,
 8281,
 8317,
 8318,
 8347,
 8349,
 8356,
 8364,
 8373,
 8375,
 8380,
 8387,
 8389,
 8398,
 8406,
 8411,
 8412,
 8416,
 8421,
 8422,
 8427,
 8431,
 8451,
 8459,
 8471,
 8476,
 8486,
 8494,
 8503,
 8504,
 8517,
 8523,
 8534,
 8535,
 8548,
 8569,
 8574,
 8579,
 8589,
 8592,
 8601,
 8603,
 8606,
 8625,
 8632,
 8648,
 8687,
 8689,
 8703,
 8716,
 8723,
 8742,
 8770,
 8779,
 8786,
 8791,
 8794,
 8805,
 8816,
 8819,
 8820,
 8863,
 8871,
 8893,
 8896,
 8909,
 8913,
 8917,
 8923,
 8938,
 8948,
 8949,
 8950,
 8963,
 8997,
 9035,
 9038,
 9041,
 9045,
 9047,
 9058,
 9063,
 9065,
 9078,
 9079,
 9091,
 9097,
 9108,
 9114,
 9136,
 9150,
 9154,
 9160,
 9171,
 9189,
 9198,
 9203,
 9208,
 9218,
 9221,
 9226,
 9230,
 9237,
 9238,
 9250,
 9261,
 9266,
 9282,
 9288,
 9291,
 9327,
 9329,
 9336,
 9347,
 9378,
 9379,
 9382,
 9389,
 9421,
 9436,
 9448,
 9468,
 9469,
 9473,
 ...]

In [56]:
pd.DataFrame(index2).to_csv("/Users/kuoloading/Downloads/index2.csv")

In [44]:
frequency.iloc[2]

TradesGroupCode    1
Name: %2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7YY%3D, dtype: int64

In [12]:
recency = sort.pivot_table('TradesDateTime1', index='MemberID',aggfunc="max")
recency

                                                       TradesDateTime1
MemberID
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909... 2019-06-26 08:31:11
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2... 2018-05-26 22:48:00
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7... 2019-04-13 02:23:27
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%... 2019-09-05 00:19:02
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf... 2016-06-24 05:22:27
...                                                                ...
zzuyFTH0qXj2h9ABnGbVDa5JG0S%2FHP8vz9VVJjGTbw4%3D   2016-06-05 05:11:53
zzvTsLQAKUueMvz%2Bvx%2FYptKHZIMMEu7nSWnkOiBhtR4%3D 2019-07-19 17:59:33
zzw%2Bk3PFtOtuOIu62cuXNkLNLUFDlgmXZj2XeMTwl2g%3D   2019-12-21 03:37:24
zzw9O6yOUvVbxgrvUGCnmjjacARx%2FbQ%2F12aZDz27TbE%3D 2019-05-14 04:36:07
zzwvJvTcevm90Q6BkxJqud94QGdwcvDOrWT88F1cTM4%3D     2018-12-27 21:21:34

[181386 rows x 1 columns]

import time
from datetime import datetime
#timestamp = int(time.mktime(datetime.now().timetuple()))
closeday = recency["TradesDateTime1"].max()

#a = int(closeday.timetuple())
timestamp = int(time.mktime(closeday.timetuple()))

now = datetime.fromtimestamp(10)
timestamp

t = table["TradesDateTime1"][10]
t1 = int(time.mktime(t.timetuple()))


c = closeday -t
timestamp = int(time.mktime(c.timetuple()))

In [30]:
table = pd.concat([recency, frequency, monetary,monetary_max],axis=1)
table

,TradesDateTime1,TradesGroupCode,TotalSalesAmount,TotalSalesAmount
MemberID,,,,
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909HvCU%3D,2019-06-26 08:31:11,1,2850.000000,2850
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2FeJJKo%3D,2018-05-26 22:48:00,1,1380.000000,1380
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7YY%3D,2019-04-13 02:23:27,1,3160.000000,3160
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%2Bt4%3D,2019-09-05 00:19:02,1,1900.000000,1900
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf3o%3D,2016-06-24 05:22:27,1,1280.000000,1280
...,...,...,...,...
zzuyFTH0qXj2h9ABnGbVDa5JG0S%2FHP8vz9VVJjGTbw4%3D,2016-06-05 05:11:53,1,1280.000000,1280
zzvTsLQAKUueMvz%2Bvx%2FYptKHZIMMEu7nSWnkOiBhtR4%3D,2019-07-19 17:59:33,1,1280.000000,1280
zzw%2Bk3PFtOtuOIu62cuXNkLNLUFDlgmXZj2XeMTwl2g%3D,2019-12-21 03:37:24,3,1813.333333,2380
zzw9O6yOUvVbxgrvUGCnmjjacARx%2FbQ%2F12aZDz27TbE%3D,2019-05-14 04:36:07,2,1330.000000,1380
zzwvJvTcevm90Q6BkxJqud94QGdwcvDOrWT88F1cTM4%3D,2018-12-27 21:21:34,8,4295.250000,9700

In [31]:
name1 = ["TradesDateTime1","TradesGroupCode","TotalSalesAmount","sum"]
table.columns = name1

In [32]:
table

,TradesDateTime1,TradesGroupCode,TotalSalesAmount,sum
MemberID,,,,
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909HvCU%3D,2019-06-26 08:31:11,1,2850.000000,2850
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2FeJJKo%3D,2018-05-26 22:48:00,1,1380.000000,1380
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7YY%3D,2019-04-13 02:23:27,1,3160.000000,3160
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%2Bt4%3D,2019-09-05 00:19:02,1,1900.000000,1900
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf3o%3D,2016-06-24 05:22:27,1,1280.000000,1280
...,...,...,...,...
zzuyFTH0qXj2h9ABnGbVDa5JG0S%2FHP8vz9VVJjGTbw4%3D,2016-06-05 05:11:53,1,1280.000000,1280
zzvTsLQAKUueMvz%2Bvx%2FYptKHZIMMEu7nSWnkOiBhtR4%3D,2019-07-19 17:59:33,1,1280.000000,1280
zzw%2Bk3PFtOtuOIu62cuXNkLNLUFDlgmXZj2XeMTwl2g%3D,2019-12-21 03:37:24,3,1813.333333,2380
zzw9O6yOUvVbxgrvUGCnmjjacARx%2FbQ%2F12aZDz27TbE%3D,2019-05-14 04:36:07,2,1330.000000,1380
zzwvJvTcevm90Q6BkxJqud94QGdwcvDOrWT88F1cTM4%3D,2018-12-27 21:21:34,8,4295.250000,9700

In [14]:
#tabel["r"] = table["TradesDateTime1"]
closeday = recency["TradesDateTime1"].max()
temp = []
for i in range(len(table)):
    temp += [(closeday - table["TradesDateTime1"][i]).days]
x = np.array(temp)
x.max()

2404

In [15]:
#所有Fare的算術平均數
mu = x.mean()
#標準差
std = x.std()
#標準化後之結果
z_temp= (x - mu) / std

print(z_temp)

[-0.79179487 -0.01192349 -0.64409195 ... -1.14037374 -0.70514249
 -0.43533851]

In [34]:
m_ = table["TotalSalesAmount"]
m_z_temp = []
m_mu = m_.mean()
m_std = m_.std()
m_z_temp= (m_ - m_mu) / m_std
print(m_z_temp)

MemberID
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909HvCU%3D      1.337501
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2FeJJKo%3D   -0.575033
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7YY%3D        1.740825
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%2Bt4%3D      0.101510
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf3o%3D       -0.705138
                                                              ...
zzuyFTH0qXj2h9ABnGbVDa5JG0S%2FHP8vz9VVJjGTbw4%3D           -0.705138
zzvTsLQAKUueMvz%2Bvx%2FYptKHZIMMEu7nSWnkOiBhtR4%3D         -0.705138
zzw%2Bk3PFtOtuOIu62cuXNkLNLUFDlgmXZj2XeMTwl2g%3D           -0.011247
zzw9O6yOUvVbxgrvUGCnmjjacARx%2FbQ%2F12aZDz27TbE%3D         -0.640085
zzwvJvTcevm90Q6BkxJqud94QGdwcvDOrWT88F1cTM4%3D              3.217835
Name: TotalSalesAmount, Length: 181386, dtype: float64

In [35]:
table["TradesGroupCode"].describe()

count    181386.000000
mean          1.924779
std           2.375565
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         342.000000
Name: TradesGroupCode, dtype: float64

In [36]:
f_ = table["TradesGroupCode"]

f_mu = f_.mean()
f_std = f_.std()
f_z_temp= (f_ - f_mu) / f_std
print(f_z_temp)

MemberID
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909HvCU%3D     -0.389288
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2FeJJKo%3D   -0.389288
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7YY%3D       -0.389288
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%2Bt4%3D     -0.389288
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf3o%3D       -0.389288
                                                              ...
zzuyFTH0qXj2h9ABnGbVDa5JG0S%2FHP8vz9VVJjGTbw4%3D           -0.389288
zzvTsLQAKUueMvz%2Bvx%2FYptKHZIMMEu7nSWnkOiBhtR4%3D         -0.389288
zzw%2Bk3PFtOtuOIu62cuXNkLNLUFDlgmXZj2XeMTwl2g%3D            0.452617
zzw9O6yOUvVbxgrvUGCnmjjacARx%2FbQ%2F12aZDz27TbE%3D          0.031664
zzwvJvTcevm90Q6BkxJqud94QGdwcvDOrWT88F1cTM4%3D              2.557379
Name: TradesGroupCode, Length: 181386, dtype: float64

In [37]:
table["r_by_days"] = x
table["r_normal"] = z_temp
table["f_normal"] = f_z_temp
table["m_normal"] = m_z_temp

In [38]:
name = ["r","f","m","m_sum","r_by_days","r_normal","f_normal","m_normal"]
table.columns = name

In [39]:
table.head(20)

,r,f,m,m_sum,r_by_days,r_normal,f_normal,m_normal
MemberID,,,,,,,,
%2B%2B%2FsALKlNdkh585nb%2F9geIrN84FIZZLkD8qf909HvCU%3D,2019-06-26 08:31:11,1,2850.000000,2850,309,-0.791795,-0.389288,1.337501
%2B%2B2Sw%2FYbIovLROVPDc%2BeVjbEdn6fTeg7niPBE%2FeJJKo%3D,2018-05-26 22:48:00,1,1380.000000,1380,705,-0.011923,-0.389288,-0.575033
%2B%2B3XVjBiQPLoAXWc7gK%2BTdvTH4J4AmgkeFlB3mmN7YY%3D,2019-04-13 02:23:27,1,3160.000000,3160,384,-0.644092,-0.389288,1.740825
%2B%2B44iA8rzzl4lYN3dzParPLqAXetHBSwDFIBUBD%2B%2Bt4%3D,2019-09-05 00:19:02,1,1900.000000,1900,239,-0.929651,-0.389288,0.101510
%2B%2B6Xs%2FwHblxbDDDYQ9osx6DMUooacHVpAJvv7KWgf3o%3D,2016-06-24 05:22:27,1,1280.000000,1280,1407,1.370576,-0.389288,-0.705138
%2B%2B6ZXiIdakH%2B77WllacG4cehkRZkwBnSIX2XvAroTko%3D,2017-09-28 22:38:00,1,3758.000000,3758,945,0.460726,-0.389288,2.518849
%2B%2B6bo8s3RbG5E3%2FFlzz1bg7Q7D3rdOd00L7AXTUHynU%3D,2017-07-30 01:24:00,1,3359.000000,3359,1006,0.580858,-0.389288,1.999733
%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbYCVE%3D,2019-01-08 22:00:34,7,1976.857143,3484,478,-0.458971,2.136427,0.201504
%2B%2B8lPULC%2BdY%2F3MWf4kbymzr1cx%2B3Eaktr2fvQHuFH78%3D,2018-12-15 02:31:16,1,1726.000000,1726,503,-0.409737,-0.389288,-0.124872
%2B%2B9RCToUG%2F8jRD0EcLzfsQPEiC7vN64HMkzGjPxlk4M%3D,2018-03-30 02:03:37,1,1280.000000,1280,763,0.102300,-0.389288,-0.705138
%2B%2BAxIR%2FMP7E3PHys4cxjjgCzWuwinageEcPXGH8SXG0%3D,2016-10-16 18:26:00,1,1280.000000,1280,1292,1.144098,-0.389288,-0.705138
%2B%2BHVWUHpauba4avsH6qa1JN3VITlhErA3GLSgNEq5SQ%3D,2019-09-21 07:18:20,2,3935.000000,5990,223,-0.961161,0.031664,2.749134
%2B%2BIQh8016M2jdnkz6608gbhHjiXKrXmUoN68bJz09mI%3D,2019-05-11 23:27:11,1,980.000000,980,355,-0.701204,-0.389288,-1.095451
%2B%2BKWWfO7UJQhmQXfJHoERSh2Ha4XnWrMJRMdMhB3xIw%3D,2018-10-02 06:37:25,1,1680.000000,1680,577,-0.264003,-0.389288,-0.184720
%2B%2BLF8KhHcEi0FHyrHxgTk2aaGagL9vgr9gJKz7AD68E%3D,2019-06-13 08:38:27,2,739.500000,1080,322,-0.766193,0.031664,-1.408352
%2B%2BNDzORK22Pw4JL39ljTf3PC0%2BIt5bhEcTIo8nVXOSc%3D,2019-10-10 05:33:26,3,1613.333333,1680,204,-0.998579,0.452617,-0.271456
%2B%2BNsfFBYc%2BjEi%2B6UABbCJFEsuCeBhFlHCKOfoB1MaVA%3D,2020-02-27 20:25:39,2,2719.500000,3259,63,-1.276260,0.031664,1.167715
%2B%2BP3hhogUcwlFXNq%2FN%2F%2BF9UFR%2BXcIHzrhS82Nu5PqD8%3D,2020-02-24 18:20:00,11,2136.363636,4060,66,-1.270352,3.820237,0.409029
%2B%2BPvI%2F%2Fh1QWEIKP1ezh7v%2BUV1%2Fp7YEYpk8KAd5wms3w%3D,2019-12-05 03:45:54,2,1680.000000,1680,148,-1.108864,0.031664,-0.184720
%2B%2BRYY9oGzdbwRFSHccbpzA%2Ft0vkUvfoqcpTwJcnhCeE%3D,2017-12-06 02:31:00,2,1480.000000,1480,877,0.326809,0.031664,-0.444929

In [40]:
table.to_csv("/Users/kuoloading/Downloads/rfm_new.csv")

In [94]:
table2 =table

In [96]:
a = pd.DataFrame()
#k = 0
for i in index5:
  #  k+=1
    #str_1 =  str(i)
    #a= pd.concat(a,table2.iloc[[i],:])
    a = pd.concat([a, table2.iloc[[i],:]], axis=0)
    ##if k ==10:
      #  break
    #table2 = table2.drop([table.index[i]])
   # print (str_1)
#table2.iloc[[1],:]

In [97]:
a

,r,f,m,m_sum,r_by_days,r_normal,f_normal,m_normal
MemberID,,,,,,,,
%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbYCVE%3D,2019-01-08 22:00:34,7,1976.857143,3484,478,-0.458971,2.136427,0.201504
%2B%2BP3hhogUcwlFXNq%2FN%2F%2BF9UFR%2BXcIHzrhS82Nu5PqD8%3D,2020-02-24 18:20:00,11,2136.363636,4060,66,-1.270352,3.820237,0.409029
%2B%2FrFyVWMWO4cpgJls1OgjyoxEc35KE2HA0HB0gKP33g%3D,2020-01-02 21:32:26,15,1701.466667,3287,119,-1.165976,5.504047,-0.156791
%2B2L3qeMLfbpnoT09K00DdiGfrvTEiK6grWnkvFlAiw0%3D,2020-02-10 04:54:21,12,1599.166667,4040,81,-1.240812,4.241189,-0.289888
%2B3ewi8VLqI8BqfOC%2F4jmUyOwhunaQjenxx0QtPTKNM8%3D,2020-02-04 17:19:59,11,1901.727273,3382,86,-1.230965,3.820237,0.103757
...,...,...,...,...,...,...,...,...
zxjVQqQsHkkJevOxObiJ3NKxSKtTPnuWyUA5NyHqH38%3D,2019-01-15 03:22:55,6,1572.000000,1880,472,-0.470787,1.715474,-0.325233
zyBezm9UGFfvCGL0MFL0HyS0OvAmMyVqHuX%2BA%2B4ZNHI%3D,2019-06-05 00:20:00,6,2070.333333,3571,331,-0.748469,1.715474,0.323121
zzA89nWMnfG4gOIB73ZFqWkd3z8N5ujHW99wAPCJ7V4%3D,2020-04-07 11:57:35,6,1775.333333,3960,23,-1.355035,1.715474,-0.060687
zzDxaBctzlencSpoNRT%2BEejnHvnJylFnYbE1m42XT6c%3D,2019-09-22 19:25:44,6,1861.666667,2630,221,-0.965100,1.715474,0.051636
zzwvJvTcevm90Q6BkxJqud94QGdwcvDOrWT88F1cTM4%3D,2018-12-27 21:21:34,8,4295.250000,9700,490,-0.435339,2.557379,3.217835

In [98]:
a.to_csv("/Users/kuoloading/Downloads/a5.csv")

In [100]:
a.head()

,r,f,m,m_sum,r_by_days,r_normal,f_normal,m_normal
MemberID,,,,,,,,
%2B%2B8NpYVoqyjmc8mROiPMlX%2F2J8JlOghaysSF3qbYCVE%3D,2019-01-08 22:00:34,7,1976.857143,3484,478,-0.458971,2.136427,0.201504
%2B%2BP3hhogUcwlFXNq%2FN%2F%2BF9UFR%2BXcIHzrhS82Nu5PqD8%3D,2020-02-24 18:20:00,11,2136.363636,4060,66,-1.270352,3.820237,0.409029
%2B%2FrFyVWMWO4cpgJls1OgjyoxEc35KE2HA0HB0gKP33g%3D,2020-01-02 21:32:26,15,1701.466667,3287,119,-1.165976,5.504047,-0.156791
%2B2L3qeMLfbpnoT09K00DdiGfrvTEiK6grWnkvFlAiw0%3D,2020-02-10 04:54:21,12,1599.166667,4040,81,-1.240812,4.241189,-0.289888
%2B3ewi8VLqI8BqfOC%2F4jmUyOwhunaQjenxx0QtPTKNM8%3D,2020-02-04 17:19:59,11,1901.727273,3382,86,-1.230965,3.820237,0.103757